### ISSUE TITLE
DB migrations

### ISSUE THREAD

**Issue by danwdart** [danwdart/projectchaplin#144]
Move over to using DB migrations so upgrades are easier

**Comment by dandart** [comment]
Almost all is ready - just needs to be automated

Although I'm not sure it's sane to check on every request, I'd suggest that there'd be maybe a notification area for the admin to do the upgrade perhaps? Or is that too much overengineering? Thinking maybe that the auto approach is better... but it does check the migration table EVERY request, which isn't very nice...

**Comment by dandart** [comment]
On branch migrations.

**Comment by dandart** [comment]
Considering making an "upgrade" button which will call this... the only proper way to upgrade is to run it... so perhaps on a git post-pull and/or docker installation that this should be run...

**Comment by kathiedart** [comment]
Any suggestions on when to automate this? Perhaps having an unversioned "version" file that is detected and if it's wrong update it?

**Comment by kathiedart** [comment]
The version file sounds like the most useful thing.

**Comment by kathiedart** [comment]
So solution:
Just migrate every time because it just checks a file and checks against DB I think

**Comment by danwdart** [comment]
Automated in docker
