### ISSUE TITLE
Ask for missing setup options required on launch, not all

### ISSUE THREAD

**Issue by danwdart** [danwdart/projectchaplin#150]
If new steps required in setup, give the user the steps after the upgrade

FOR ADMINS ONLY

**Comment by kathiedart** [comment]
Right now that doesn't exist
But I think all this is is "if this option doesn't exist in your setup, ask you"
instead of "ask you everything if you don't have a setup".

**Comment by danwdart** [comment]
Irrelevant - now using envs
