### ISSUE TITLE
env overwriting for docker

### ISSUE THREAD

**Issue by danwdart** [danwdart/projectchaplin#153]
If configured for docker the IP addresses of docker hosts should be set to overwrite the config files.
This would make it easier to stay setup if one turns off and on the server often.

**Comment by kathiedart** [comment]
Not sure how good this is
May just have to preset an IP and fill in half the config files and make the config tool ask for only the rest (i.e. API keys)

**Comment by kathiedart** [comment]
This is presetting the IP, the rest is covered in #150

**Comment by kathiedart** [comment]
this is blocked by "continue setup"

**Comment by danwdart** [comment]
Ignore - docker has hosts
