### ISSUE TITLE
Create an admin user on setup

### ISSUE THREAD

**Issue by danwdart** [danwdart/projectchaplin#159]
No point having to create one manually

**Comment by kathiedart** [comment]
Put this in the setup step

**Comment by kathiedart** [comment]
Is blocked by #178

**Comment by kathiedart** [comment]
Who should be the admin?

Username
Email
Password
Password2

then create at user level 5

**Comment by kathiedart** [comment]
I'd ignore that it would be blocked in fact, we can get this out without

**Comment by danwdart** [comment]
Should be in env

**Comment by danwdart** [comment]
Single service for docker?

**Comment by danwdart** [comment]
Done and added to Docker and README.md
