### ISSUE TITLE
Split up docker so that it's easier to maintain

### ISSUE THREAD

**Issue by danwdart** [danwdart/projectchaplin#174]
Use compose to split up everything into factory standard pieces
such as a PHP piece, a Node piece, an Nginx piece etc

Makes the images smaller and more reusable

**Comment by kathiedart** [comment]
```
docker -f Dockerfile-php -t chaplin-php build .
docker -f Dockerfile-node -t chaplin-node build .
```
etc

**Comment by danwdart** [comment]
This is now done and makes things a lot easier going forward.
