### ISSUE TITLE
Nodes that don't support video uploads

### ISSUE THREAD

**Issue by danwdart** [danwdart/projectchaplin#24]
Allow nodes that you don't want uploads for
They'll cluster and use other nodes to view and upload from

**Comment by dandart** [comment]
We can easily disable this - assigning soon

**Comment by danwdart** [comment]
Should be an env soon

**Comment by danwdart** [comment]
This seems to imply no importing either because importing may require an extra encoding step. Disabling these functions as an env option seems like the best idea.

**Comment by danwdart** [comment]
This is implemented now via an env variable, to use it set "NO_UPLOADS=true" in your .env
